/**
 * 项目管理
 * 返回值数据格式：JSON  错误消息：遵循HTTP Response Status Codes  示例：  200, \"OK\"  400, \"Bad Request\"  404, \"Not Found\"  500, \"Internal Server Error\"
 *
 * OpenAPI spec version: v1.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * @property `[createdAt]` 创建人username
 * @property `[createdName]` 创建人Name
 * @property `id` id
 * @property `projectId` 项目ID
 * @property `[sectionId]` 任务组ID
 * @property `[sectionName]` 任务组名称
 * @property `statusPhase` 任务状态阶段
 * @property `taskClassId` 任务分类Id
 * @property `[taskClassName]` 任务分类名称
 * @property `taskId` 任务Id
 * @property `[taskTypeGroup]` 标识是否是bug
 * @property `taskTypeId` 任务类型Id
 * @property `[taskTypeName]` 任务类型名称
 * @property `title` 任务标题
 */
export interface TaskBaseModelModel {
  /**
   * 创建人username
   */
  createdAt?: string;
  /**
   * 创建人Name
   */
  createdName?: string;
  /**
   * id
   */
  id: number;
  /**
   * 项目ID
   */
  projectId: string;
  /**
   * 任务组ID
   */
  sectionId?: string;
  /**
   * 任务组名称
   */
  sectionName?: string;
  /**
   * 任务状态阶段
   */
  statusPhase: TaskBaseModel.StatusPhaseEnum;
  /**
   * 任务分类Id
   */
  taskClassId: number;
  /**
   * 任务分类名称
   */
  taskClassName?: string;
  /**
   * 任务Id
   */
  taskId: string;
  /**
   * 标识是否是bug
   */
  taskTypeGroup?: string;
  /**
   * 任务类型Id
   */
  taskTypeId: number;
  /**
   * 任务类型名称
   */
  taskTypeName?: string;
  /**
   * 任务标题
   */
  title: string;
}

export namespace TaskBaseModel {
  export enum StatusPhaseEnum {
    /**
     * `BEGIN` 任务状态阶段
     */
    BEGIN = <any>'BEGIN',
    /**
     * `MIDDLE` 任务状态阶段
     */
    MIDDLE = <any>'MIDDLE',
    /**
     * `END` 任务状态阶段
     */
    END = <any>'END'
  }
}
